version: '3.4'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    volumes:
      - mongo-data:/data/db

  chroma:
    build: ../chroma/
    restart: always
    ports:
      - ${CHROMA_DB_PORT}:${CHROMA_DB_PORT}
    volumes:
      - chroma-data:/data/db

  server:
    build: ./
    restart: unless-stopped
    depends_on:
      - mongo
      - chroma
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

volumes:
  mongo-data:
  chroma-data:
