version: "3.9"

x-server-env: &server-env
  DOCUMENT_DB_HOST: mongo
  EMBEDDING_DB_HOST: chroma
  REDIS_URL: redis
  RABBIT_HOST: rabbit

services:
  mongo:
    image: mongo:7.0.5
    restart: unless-stopped
    ports:
      - ${DOCUMENT_DB_PORT}:${DOCUMENT_DB_PORT}
    volumes:
      - mongo-data-v2:/data/db
    networks:
      - default

  chroma:
    image: ghcr.io/chroma-core/chroma:0.4.24
    restart: unless-stopped
    volumes:
      - chroma-data-v2:/chroma
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - ${EMBEDDING_DB_PORT}:${EMBEDDING_DB_PORT}
    networks:
      - default

  rabbit:
    image: rabbitmq:3.13.0-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default

  server:
    build: ./
    volumes:
      - embedder-cache:/root/.cache/chroma/
    depends_on:
      - mongo
      - chroma
      - fetcher_workers
      - parser_workers
      - redis
    env_file:
      - .env
    environment:
      <<: *server-env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - default
    command: [python, -m, robojudge.main]

  fetcher_workers:
    build: ./
    restart: unless-stopped
    volumes:
      - embedder-cache:/root/.cache/chroma/
    depends_on:
      - mongo
      - chroma
      - rabbit
    env_file:
      - .env
    environment:
      <<: *server-env
    networks:
      - default
    command:
      [
        dramatiq,
        robojudge.tasks.scraping_scheduler,
        --processes,
        "1",
        --threads,
        "1",
        --queues,
        fetching-queue,
      ]

  parser_workers:
    build: ./
    restart: unless-stopped
    volumes:
      - embedder-cache:/root/.cache/chroma/
    depends_on:
      - mongo
      - chroma
      - rabbit
    env_file:
      - .env
    environment:
      <<: *server-env
    networks:
      - default
    command:
      [
        dramatiq,
        robojudge.tasks.scraping_scheduler,
        --processes,
        "1",
        --threads,
        "1",
        --queues,
        parsing-queue,
      ]

  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    restart: unless-stopped
    depends_on:
      - server
    env_file:
      - .env
    environment:
      DOCUMENT_DB_HOST: mongo
      EMBEDDING_DB_HOST: chroma
      REDIS_URL: redis
      RABBIT_HOST: rabbit
    ports:
      - ${CLIENT_PORT}:80
    networks:
      - default

  redis:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - default

volumes:
  embedder-cache:
  mongo-data-v2:
  chroma-data-v2:

networks:
  default:
    name: robojudge-network
