version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    volumes:
      - mongo-data:/data/db
    networks:
      - default

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index-data:/chroma
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - ${CHROMA_DB_PORT}:${CHROMA_DB_PORT}
    networks:
      - default

  server:
    build: ./
    restart: unless-stopped
    depends_on:
      - mongo
      - chroma
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - default

  client:
    build: ./client
    restart: unless-stopped
    depends_on:
      - server
    env_file:
      - .env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    networks:
      - default

volumes:
  mongo-data:
  index-data:

networks:
  default:
      name: robojudge-network
