version: "3.9"

services:
  mongo:
    image: mongo:7.0.5
    restart: always
    ports:
      - ${DOCUMENT_DB_PORT}:${DOCUMENT_DB_PORT}
    volumes:
      - mongo-data:/data/db
    networks:
      - default

  chroma:
    image: ghcr.io/chroma-core/chroma:0.4.24
    restart: unless-stopped
    volumes:
      - chroma-data:/chroma
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - ${EMBEDDING_DB_PORT}:${EMBEDDING_DB_PORT}
    networks:
      - default

  server:
    build: ./
    restart: unless-stopped
    volumes:
      - embedder-cache:/root/.cache/chroma/
    depends_on:
      - mongo
      - chroma
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - default

  client:
    build: 
      context: ./
      dockerfile: ./client/Dockerfile
    restart: unless-stopped
    depends_on:
      - server
    env_file:
      - .env
    ports:
      - ${CLIENT_PORT}:80
    networks:
      - default

  redis:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - default


volumes:
  embedder-cache:
  mongo-data:
  chroma-data:

networks:
  default:
      name: robojudge-network
